Added Retry policy to API Client
openx/OX3-Python-API-Client pull request #46
Opened 2021-03-10 11:17 UTC by ox-mtworek

Fix for SSO connection timeouts, similar to: https://github.com/openx/oxbot-api/pull/45/

example error from oxbot tests:
```
ConnectionError: HTTPSConnectionPool(host='test-sso.openx.org', port=443): Max retries exceeded with url: /api/index/initiate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0fe53ddac8>: Failed to establish a new connection: [Errno 110] Connection timed out',))	
18:30:11.110	DEBUG	Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/oxbot/pdm/pdm.py", line 326, in pdm_start_suite
    self._set_suite_variables(suite, suite.pub_instance, suite.pub_user, suite.pub_definition, pub_host)
  File "/usr/local/lib/python3.6/site-packages/oxbot/pdm/pdm.py", line 176, in _set_suite_variables
    self.login(user=user, instance=instance, instance_data=instance_data)
  File "/usr/local/lib/python3.6/site-packages/oxbot/pdm/pdm.py", line 139, in login
    self.api_request.api_login(self.SUITES[suite_name].environment, instance, user, password)
  File "/usr/local/lib/python3.6/site-packages/oxbot/api/decorators/loggers.py", line 42, in function_wrapper
    output = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oxbot/api/APIRequests.py", line 120, in api_login
    self.api.token = self._login_and_get_access_token(instance_id, email, password, custom_token)
  File "/usr/local/lib/python3.6/site-packages/oxbot/api/APIRequests.py", line 722, in _login_and_get_access_token
    return self._ox3apiclient_login(email, password)
  File "/usr/local/lib/python3.6/site-packages/oxbot/api/APIRequests.py", line 748, in _ox3apiclient_login
    self.api.ox3api.logon(email=email, password=password)
  File "/usr/local/lib/python3.6/site-packages/ox3apiclient/__init__.py", line 260, in logon
    self.fetch_request_token()
  File "/usr/local/lib/python3.6/site-packages/ox3apiclient/__init__.py", line 165, in fetch_request_token
    response = self._session.post(url=self.request_token_url, auth=oauth, timeout=self.timeout)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
```

2021-03-10 16:10 UTC, KamilKoziolO approved these changes
LGTM

2021-03-10 22:00 UTC, psztur requested changes
This client is for authentication with SSO and provides plain methods for sending requests to API.  In my opinion you should handle potential retry logic outside of it - when invokng this client's methods, so you (your software) controls how you want to handle potential exceptions.  This way we are sure nothing gets lost - API client still provides only an abstraction of how to talk to API and only (and always) returns to you what API said.

If those words do not convince you, then I will ask you to change this hardcoded retry-logic into something client can setup and control on the request-basis - so that client may or may not set retry mechanis for each request separately and adjust its parameters (on what exceptions, http errors should retry, how often and for how long it should wait).

2021-03-10 22:04 UTC, ikari-pl commented
I agree that:
* the retry logic belongs to the application
* if it *has to* be in the authentication client, it should be highly customizable and off by default

Suggestions:
* make it parametrizable and optional
* document the optional config well in docstring - this is an open source public client intended to be used by the wide world, not by OpenX

2021-03-11 06:20 UTC, przemyslaw-sitek approved these changes

2021-03-11 09:56 UTC, ox-mtworek commented
@psztur , @ikari-pl your arguments sounds convincing to me
We can close this PR
Thanks for your comments

2021-03-11 09:56 UTC, closed without merging